### ISSUE TITLE
Recreating the mohawk hairstyle latent mapper / where' s the latents for training ? train_faces.pt /test_faces.pt

### ISSUE THREAD

**Issue by johndpope** [orpatashnik/StyleCLIP#59]
I save the 
model_ir_se50.pth
stylegan2-ffhq-config-f.pt into pretrained_models

I run the code - but hit this error

```python

python scripts/train.py --exp_dir ../results/clown_hairstyle --no_fine_mapper --description "clown hairstyle"

{'batch_size': 2,
 'board_interval': 50,
 'checkpoint_path': None,
 'clip_lambda': 1.0,
 'description': 'clown hairstyle',
 'exp_dir': '../results/clown_hairstyle',
 'id_lambda': 0.1,
 'image_interval': 100,
 'ir_se50_weights': '../pretrained_models/model_ir_se50.pth',
 'latent_l2_lambda': 0.8,
 'latents_test_path': 'test_faces.pt',
 'latents_train_path': 'train_faces.pt',
 'learning_rate': 0.5,
 'mapper_type': 'LevelsMapper',
 'max_steps': 50000,
 'no_coarse_mapper': False,
 'no_fine_mapper': True,
 'no_medium_mapper': False,
 'optim_name': 'ranger',
 'save_interval': 2000,
 'stylegan_size': 1024,
 'stylegan_weights': '../pretrained_models/stylegan2-ffhq-config-f.pt',
 'test_batch_size': 1,
 'test_dataset_size': 1000,
 'test_workers': 2,
 'train_dataset_size': 5000,
 'val_interval': 2000,
 'work_in_stylespace': False,
 'workers': 4}
Loading decoder weights from pretrained!
Loading ResNet ArcFace
Traceback (most recent call last):
  File "scripts/train.py", line 32, in <module>
    main(opts)
  File "scripts/train.py", line 26, in main
    coach = Coach(opts)
  File "../mapper/training/coach.py", line 43, in __init__
    self.train_dataset, self.test_dataset = self.configure_datasets()
  File "../mapper/training/coach.py", line 184, in configure_datasets
    train_latents = torch.load(self.opts.latents_train_path)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'train_faces.pt'
```

**Comment by johndpope** [comment]
sorry 


To this end, we provide the CelebA-HQ that was inverted by e4e:
--
115 | [train set](https://drive.google.com/file/d/1gof8kYc_gDLUT4wQlmUdAtPnQIlCO26q/view?usp=sharing), [test set](https://drive.google.com/file/d/1j7RIfmrCoisxx3t-r-KC02Qc8barBecr/view?usp=sharing).
